vich_uploader:
    db_driver: orm

    mappings:
        products_image:
            uri_prefix: /img/uploads
            upload_destination: '%kernel.project_dir%/public/img/uploads'
            namer: vich_uploader.namer_uniqid
