<?php

namespace App\Repository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDescDate()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->orderBy('p.updatedAt','DESC');
        return $qb->getQuery()->getResult();
    }
}