<?php

namespace App\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDescDate()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->orderBy('p.updatedAt','DESC');
        return $qb->getQuery()->getResult();
    }
    public function findLastProject()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->orderBy('p.updatedAt','DESC')
        ->setMaxResults(1);
        $result = $qb->getQuery()->getResult();
        if($result){
            $lastProject = $result[0];
        }else{
            $lastProject = null;
        }
        ;
        return $lastProject;
    }
}